Nama: Ahmad Nasrudin Jamil

NIM : 210411100098

Kelas : Pencarian dan Penambangan Web B

# Singular Value Decomposition (SVD)

## Library yang digunakan

In [127]:
import gdown
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from numpy import array, diag, zeros
from scipy.linalg import svd
from numpy import array
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
import pickle

In [128]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\EBC
[nltk_data]     KOMPUTER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [129]:
file_id = '1-tr5TV3kjdvsHocZM3f7KoDA_ZEIAJwR'
url = f'https://drive.google.com/uc?id={file_id}'
output = 'crawling_2_kategori.csv'

# Unduh file dari Google Drive
gdown.download(url, output, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1-tr5TV3kjdvsHocZM3f7KoDA_ZEIAJwR
To: C:\Users\EBC KOMPUTER\Documents\Jupyter Notebook\PPW\Tugas 6\crawling_2_kategori.csv
100%|███████████████████████████████████████████████████████████████████████████████| 260k/260k [00:00<00:00, 2.23MB/s]


'crawling_2_kategori.csv'

In [130]:
# Membaca file CSV ke DataFrame
df = pd.read_csv(output)

## Contoh Sederhana Implementasi SVD

In [131]:
A = array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Original Matrix A:\n", A)

# Singular-value decomposition
U, s, VT = svd(A)

# Display U, s (singular values), and VT
print("\nMatrix U (Left Singular Vectors):\n", U)
print("\nSingular Values (s):\n", s)
print("\nMatrix VT (Right Singular Vectors Transpose):\n", VT)

# Create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

print("\nMatrix Sigma (Diagonal Matrix with Singular Values):\n", Sigma)

# Select the number of components to keep
n_elements = 3
Sigma_reduced = Sigma[:, :n_elements]
VT_reduced = VT[:n_elements, :]

print("\nReduced Sigma Matrix:\n", Sigma_reduced)
print("\nReduced VT Matrix:\n", VT_reduced)

# Reconstruct A using reduced components
B = U.dot(Sigma_reduced.dot(VT_reduced))
print("\nReconstructed Matrix B (Approximation of A):\n", B)

# Transformations
T1 = U.dot(Sigma_reduced)
print("\nTransformation T1 (U * Reduced Sigma):\n", T1)

T2 = A.dot(VT_reduced.T)
print("\nTransformation T2 (A * Reduced VT.T):\n", T2)

Original Matrix A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix U (Left Singular Vectors):
 [[ 0.20673589  0.88915331  0.40824829]
 [ 0.51828874  0.25438183 -0.81649658]
 [ 0.82984158 -0.38038964  0.40824829]]

Singular Values (s):
 [2.54368356e+01 1.72261225e+00 5.14037515e-16]

Matrix VT (Right Singular Vectors Transpose):
 [[ 0.40361757  0.46474413  0.52587069  0.58699725]
 [-0.73286619 -0.28984978  0.15316664  0.59618305]
 [ 0.44527162 -0.83143156  0.32704826  0.05911168]
 [ 0.3189564  -0.09338934 -0.77009054  0.54452347]]

Matrix Sigma (Diagonal Matrix with Singular Values):
 [[2.54368356e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.72261225e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.14037515e-16 0.00000000e+00]]

Reduced Sigma Matrix:
 [[2.54368356e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.72261225e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.14037515e-16]]

Reduced VT Matrix:
 [[ 0.40361757  0.46474

In [132]:
A = array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("\nMatrix A\n", A)
# svd
svd_t = TruncatedSVD(n_components=3)
svd_t.fit(A)
result = svd_t.transform(A)
print("\nHasil\n", result)


Matrix A
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Hasil
 [[ 5.25870689e+00 -1.53166638e+00  1.11022302e-16]
 [ 1.31836254e+01 -4.38201263e-01  2.22044605e-16]
 [ 2.11085440e+01  6.55263852e-01 -8.88178420e-16]]


In [133]:
# MEngalikan Matrik U Sigma dan VT untuk mengamblikan nilai dari Matriks A
A_reconstructed = U @ Sigma @ VT

print(A_reconstructed)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


## Implementasi Code

### SVD

In [164]:
# Memuat DataFrame TF-IDF dari file
with open("tfidf_matrix.pkl", "rb") as f:
    tfidf_df_loaded = pickle.load(f)

# Menampilkan matrix TF-IDF asli
print("Original Matrix (TF-IDF Data):\n")
tfidf_df_loaded

Original Matrix (TF-IDF Data):



00       000        01  016   02   05  062        08        09  090  \
0   0.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
1   0.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
2   0.000000  0.084503  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
3   0.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
4   0.000000  0.215746  0.064396  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
..       ...       ...       ...  ...  ...  ...  ...       ...       ...  ...   
75  0.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
76  0.000000  0.026394  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
77  0.129653  0.112729  0.000000  0.0  0.0  0.0  0.0  0.044188  0.032413  0.0   
78  0.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   
79  0.000000  0.000000  0.000000  0.0  0.0  0.0  0.0  0.000000  0.000000  0.0   

    ...  youtuber  yudi  yunani     zaman       zat  zeus  zhongli  zidane  \
0   ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   
1   ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   
2   ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   
3   ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   
4   ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   
..  ...       ...   ...     ...       ...       ...   ...      ...     ...   
75  ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   
76  ...       0.0   0.0     0.0  0.000000  0.041648   0.0      0.0     0.0   
77  ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   
78  ...       0.0   0.0     0.0  0.033521  0.000000   0.0      0.0     0.0   
79  ...       0.0   0.0     0.0  0.000000  0.000000   0.0      0.0     0.0   

    zona  zone  
0    0.0   0.0  
1    0.0   0.0  
2    0.0   0.0  
3    0.0   0.0  
4    0.0   0.0  
..   ...   ...  
75   0.0   0.0  
76   0.0   0.0  
77   0.0   0.0  
78   0.0   0.0  
79   0.0   0.0  

[80 rows x 4558 columns]

In [135]:
# Singular-value decomposition pada matriks TF-IDF
U, s, VT = svd(tfidf_df_loaded.values)

In [136]:
print("\nMatrix U (Left Singular Vectors):\n")

U_df = pd.DataFrame(U, index=tfidf_df_loaded.index)
U_df


Matrix U (Left Singular Vectors):



0         1         2         3         4         5         6   \
0  -0.091595  0.056175 -0.013910  0.013600 -0.056749  0.076140 -0.005380   
1  -0.079258  0.059292 -0.018920  0.009940 -0.008689 -0.217029  0.015392   
2  -0.183313 -0.159391  0.222948 -0.153214  0.084454 -0.034873 -0.070092   
3  -0.085694  0.065664 -0.001496 -0.009067 -0.010656  0.068243 -0.000933   
4  -0.163776 -0.119838  0.141876 -0.050956  0.023441 -0.004871  0.077091   
..       ...       ...       ...       ...       ...       ...       ...   
75 -0.086467  0.047592 -0.021421  0.022420 -0.074852 -0.013050  0.038546   
76 -0.142251  0.221229 -0.030271 -0.018396  0.086705  0.157385 -0.027456   
77 -0.110903 -0.089333 -0.003546  0.068150 -0.121351 -0.010640 -0.024406   
78 -0.112207  0.025948  0.006470 -0.021871 -0.030227 -0.012504  0.011566   
79 -0.090908  0.010854 -0.022121  0.024803 -0.089617  0.023156  0.027111   

          7         8         9   ...        70        71        72        73  \
0   0.100621 -0.031858  0.144257  ...  0.001108 -0.025361  0.030205  0.011792   
1   0.113790 -0.014875 -0.140491  ... -0.010535  0.128380  0.025923 -0.084281   
2  -0.072779 -0.145116  0.003282  ... -0.094417  0.089152 -0.493488 -0.147561   
3   0.122347 -0.027605 -0.092737  ... -0.009079 -0.007248  0.005850 -0.001309   
4   0.013410  0.365324 -0.010642  ...  0.088125 -0.033186  0.359603  0.137411   
..       ...       ...       ...  ...       ...       ...       ...       ...   
75  0.276871 -0.117061  0.476740  ... -0.001508 -0.048813 -0.019465  0.042590   
76 -0.229481  0.028315  0.176335  ... -0.056872 -0.000407  0.047331 -0.081236   
77 -0.078390  0.085084 -0.022698  ... -0.046286 -0.019721 -0.000557 -0.009137   
78  0.152610 -0.032967 -0.034639  ... -0.030289  0.009300 -0.026888 -0.047221   
79  0.216573 -0.057393  0.054415  ...  0.003446  0.011957 -0.006535  0.021272   

          74        75        76        77        78        79  
0  -0.000254 -0.010223  0.000921 -0.010417  0.004322 -0.017554  
1  -0.400047  0.049301 -0.004373  0.018120  0.010422 -0.011909  
2   0.067324  0.019561  0.034262  0.027910  0.035429  0.009986  
3  -0.004256 -0.000317  0.007703  0.001554 -0.006302 -0.002612  
4  -0.020569 -0.020493  0.005489  0.183946 -0.055806 -0.013297  
..       ...       ...       ...       ...       ...       ...  
75  0.000330  0.016786 -0.004756 -0.000815  0.002209  0.008944  
76  0.208511 -0.036997 -0.002908 -0.013842 -0.000607 -0.016130  
77 -0.019203 -0.038822 -0.016659 -0.016435  0.007352  0.006620  
78  0.012751  0.005310 -0.014297 -0.018017 -0.019623  0.004836  
79  0.012706  0.000511 -0.014679 -0.015759  0.003609 -0.004779  

[80 rows x 80 columns]

In [137]:
print("\nSingular Values (s):\n")

s_df = pd.DataFrame(s, columns=["Singular Values"])
s_df


Singular Values (s):



Singular Values
0          2.726902
1          1.901217
2          1.787119
3          1.691679
4          1.473199
..              ...
75         0.496751
76         0.477644
77         0.453036
78         0.420162
79         0.394399

[80 rows x 1 columns]

In [138]:
print("\nMatrix VT (Right Singular Vectors Transpose):\n")

VT_df = pd.DataFrame(VT, columns=tfidf_df_loaded.columns)
VT_df


Matrix VT (Right Singular Vectors Transpose):



00       000        01       016        02        05       062  \
0    -0.014014 -0.057998 -0.006032 -0.001604 -0.001400 -0.003016 -0.001642   
1    -0.015694 -0.047413 -0.006073 -0.002160  0.000487 -0.003637 -0.001807   
2     0.000487  0.031083  0.006888 -0.001457 -0.000108 -0.002437 -0.001806   
3     0.017483  0.041273 -0.003196  0.003319  0.000758  0.005558  0.002886   
4    -0.035019 -0.009823  0.000274 -0.008135 -0.001360 -0.013877 -0.008120   
...        ...       ...       ...       ...       ...       ...       ...   
4553  0.002201  0.002622 -0.000270 -0.000002  0.000012 -0.000015  0.000096   
4554 -0.000281  0.000811 -0.000227 -0.000049  0.000200 -0.000046  0.000065   
4555  0.005194 -0.036490  0.001584  0.000174 -0.000255  0.001016 -0.000079   
4556  0.003173 -0.001472  0.000060 -0.007504  0.000230 -0.002999  0.000885   
4557 -0.000329  0.000533  0.000142  0.000083  0.000238  0.000019  0.000035   

            08        09       090  ...  youtuber      yudi    yunani  \
0    -0.001797 -0.008565 -0.001642  ... -0.001348 -0.014227 -0.002617   
1    -0.002076 -0.008933 -0.001807  ... -0.000417 -0.009981 -0.002031   
2    -0.000088  0.001139 -0.001806  ... -0.000366 -0.009779 -0.000380   
3     0.001780  0.010364  0.002886  ...  0.000448  0.014204  0.003044   
4    -0.003640 -0.020863 -0.008120  ... -0.001535 -0.045873 -0.006581   
...        ...       ...       ...  ...       ...       ...       ...   
4553 -0.000071  0.001422  0.000393  ...  0.000039  0.000815 -0.005769   
4554 -0.000135 -0.000093  0.000151  ...  0.000014  0.000793  0.000052   
4555  0.001313 -0.000246  0.000856  ...  0.000634 -0.003275 -0.000481   
4556 -0.000041 -0.000554  0.000820  ...  0.000006  0.001157 -0.002175   
4557 -0.000092  0.000277  0.000153  ...  0.000033  0.000341  0.000524   

         zaman       zat      zeus   zhongli    zidane      zona      zone  
0    -0.005390 -0.010752 -0.001833 -0.001811 -0.014323 -0.004815 -0.002466  
1    -0.002676  0.017696 -0.001850 -0.002471 -0.007613 -0.004629 -0.002884  
2     0.005164 -0.002897 -0.000300 -0.000129  0.014110 -0.002876  0.004860  
3    -0.004789 -0.000685  0.002853  0.009542 -0.008281  0.006940 -0.004554  
4     0.000217  0.002207 -0.005846  0.008255  0.005663 -0.017346  0.002570  
...        ...       ...       ...       ...       ...       ...       ...  
4553 -0.000173 -0.000044  0.993650  0.000061 -0.000552  0.000068  0.000536  
4554  0.000105  0.000034  0.000070  0.996049  0.000041 -0.000119  0.000023  
4555  0.002749  0.000996 -0.000576 -0.000012  0.860762  0.000427  0.000034  
4556 -0.000270  0.000586 -0.000006 -0.000096  0.002217  0.981953  0.000043  
4557  0.002344  0.000174  0.000502  0.000029  0.000017  0.000221  0.995210  

[4558 rows x 4558 columns]

In [139]:
# Membuat Sigma sebagai matriks diagonal
Sigma = np.zeros((U.shape[0], VT.shape[1]))
np.fill_diagonal(Sigma, s)

# Menampilkan Sigma sebagai DataFrame
print("\nMatrix Sigma (Diagonal Matrix with Singular Values):\n")
Sigma_df = pd.DataFrame(Sigma)

# Menampilkan DataFrame Sigma
Sigma_df


Matrix Sigma (Diagonal Matrix with Singular Values):



0         1         2         3         4     5     6     7     8     \
0   2.726902  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
1   0.000000  1.901217  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
2   0.000000  0.000000  1.787119  0.000000  0.000000   0.0   0.0   0.0   0.0   
3   0.000000  0.000000  0.000000  1.691679  0.000000   0.0   0.0   0.0   0.0   
4   0.000000  0.000000  0.000000  0.000000  1.473199   0.0   0.0   0.0   0.0   
..       ...       ...       ...       ...       ...   ...   ...   ...   ...   
75  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
76  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
77  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
78  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
79  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   

    9     ...  4548  4549  4550  4551  4552  4553  4554  4555  4556  4557  
0    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..   ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
75   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
76   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
77   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
79   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[80 rows x 4558 columns]

In [140]:
n_elements = 2600  # jumlah komponen untuk reduksi
Sigma_reduced = Sigma[:, :n_elements]
VT_reduced = VT[:n_elements, :]

# Membuat DataFrame untuk Sigma_reduced
Sigma_reduced_df = pd.DataFrame(Sigma_reduced)
print("\nReduced Sigma Matrix as DataFrame:\n")
Sigma_reduced_df


Reduced Sigma Matrix as DataFrame:



0         1         2         3         4     5     6     7     8     \
0   2.726902  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
1   0.000000  1.901217  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
2   0.000000  0.000000  1.787119  0.000000  0.000000   0.0   0.0   0.0   0.0   
3   0.000000  0.000000  0.000000  1.691679  0.000000   0.0   0.0   0.0   0.0   
4   0.000000  0.000000  0.000000  0.000000  1.473199   0.0   0.0   0.0   0.0   
..       ...       ...       ...       ...       ...   ...   ...   ...   ...   
75  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
76  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
77  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
78  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   
79  0.000000  0.000000  0.000000  0.000000  0.000000   0.0   0.0   0.0   0.0   

    9     ...  2590  2591  2592  2593  2594  2595  2596  2597  2598  2599  
0    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4    0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..   ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
75   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
76   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
77   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
78   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
79   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[80 rows x 2600 columns]

In [141]:
# Membuat DataFrame untuk VT_reduced
VT_reduced_df = pd.DataFrame(VT_reduced, columns=tfidf_df_loaded.columns)
print("\nReduced VT Matrix as DataFrame:\n")
VT_reduced_df


Reduced VT Matrix as DataFrame:



00       000        01       016        02        05       062  \
0    -0.014014 -0.057998 -0.006032 -0.001604 -0.001400 -0.003016 -0.001642   
1    -0.015694 -0.047413 -0.006073 -0.002160  0.000487 -0.003637 -0.001807   
2     0.000487  0.031083  0.006888 -0.001457 -0.000108 -0.002437 -0.001806   
3     0.017483  0.041273 -0.003196  0.003319  0.000758  0.005558  0.002886   
4    -0.035019 -0.009823  0.000274 -0.008135 -0.001360 -0.013877 -0.008120   
...        ...       ...       ...       ...       ...       ...       ...   
2595 -0.000125 -0.000078 -0.000032 -0.000037  0.000080 -0.000009  0.000020   
2596 -0.000544 -0.001205  0.000117 -0.000189 -0.001975 -0.000102  0.000139   
2597  0.000296  0.003459  0.000723  0.000111 -0.002435  0.000419  0.001572   
2598 -0.001261  0.000348  0.000051  0.000082  0.000232  0.000105  0.000178   
2599 -0.000097 -0.000069  0.000030  0.000017  0.000152  0.000074 -0.000030   

            08        09       090  ...  youtuber      yudi    yunani  \
0    -0.001797 -0.008565 -0.001642  ... -0.001348 -0.014227 -0.002617   
1    -0.002076 -0.008933 -0.001807  ... -0.000417 -0.009981 -0.002031   
2    -0.000088  0.001139 -0.001806  ... -0.000366 -0.009779 -0.000380   
3     0.001780  0.010364  0.002886  ...  0.000448  0.014204  0.003044   
4    -0.003640 -0.020863 -0.008120  ... -0.001535 -0.045873 -0.006581   
...        ...       ...       ...  ...       ...       ...       ...   
2595 -0.000015 -0.000718  0.000043  ... -0.000004 -0.000043  0.000191   
2596 -0.000026 -0.003508  0.000760  ...  0.000066 -0.000899  0.000181   
2597  0.000796  0.003066  0.000858  ...  0.000131  0.001873 -0.000084   
2598 -0.000008 -0.000572  0.000065  ...  0.000071  0.000024 -0.000186   
2599  0.000036 -0.000384  0.000279  ...  0.000001 -0.001477  0.000014   

         zaman       zat      zeus   zhongli    zidane      zona      zone  
0    -0.005390 -0.010752 -0.001833 -0.001811 -0.014323 -0.004815 -0.002466  
1    -0.002676  0.017696 -0.001850 -0.002471 -0.007613 -0.004629 -0.002884  
2     0.005164 -0.002897 -0.000300 -0.000129  0.014110 -0.002876  0.004860  
3    -0.004789 -0.000685  0.002853  0.009542 -0.008281  0.006940 -0.004554  
4     0.000217  0.002207 -0.005846  0.008255  0.005663 -0.017346  0.002570  
...        ...       ...       ...       ...       ...       ...       ...  
2595  0.000054  0.000445  0.000192 -0.000005  0.000344 -0.000048 -0.000015  
2596  0.000235  0.000274  0.000094  0.000339  0.000436 -0.000198 -0.000019  
2597 -0.000046 -0.000184 -0.000079  0.001483 -0.000417  0.000187 -0.000072  
2598 -0.000167  0.001103 -0.000207  0.000167  0.000662  0.000048  0.000198  
2599  0.000195 -0.001219 -0.000073  0.000217  0.000235  0.000147  0.000009  

[2600 rows x 4558 columns]

In [142]:
B = U.dot(Sigma_reduced.dot(VT_reduced))
B_df = pd.DataFrame(B, index=tfidf_df_loaded.index, columns=tfidf_df_loaded.columns)

print("\nReconstructed Matrix B (Approximation of Original Matrix)e:\n")
B_df


Reconstructed Matrix B (Approximation of Original Matrix)e:



00           000            01           016            02  \
0  -4.677660e-17 -1.256048e-16  1.191606e-17  4.293822e-18 -1.456516e-17   
1   6.510200e-17  1.154506e-17 -3.214659e-17  1.312647e-17 -1.066838e-17   
2  -4.818932e-17  8.450328e-02 -3.444375e-17 -1.241814e-17 -5.439646e-18   
3  -5.753174e-18  2.303252e-17 -3.554235e-17 -1.510736e-18  1.371929e-17   
4  -2.231355e-17  2.157461e-01  6.439623e-02 -5.461457e-18 -1.770934e-17   
..           ...           ...           ...           ...           ...   
75  1.224741e-17 -1.258776e-17  9.448653e-18  3.858341e-17 -2.063753e-17   
76 -4.313203e-17  2.639381e-02 -4.229236e-17 -9.127055e-17 -6.336061e-17   
77  1.296532e-01  1.127294e-01  4.627595e-17 -1.945984e-17  3.190519e-17   
78  7.539017e-18  5.151612e-17  7.702918e-17  4.029240e-17  3.178934e-16   
79  2.123546e-17 -1.290963e-17  7.189700e-17  1.626282e-17  2.877424e-17   

              05           062            08            09           090  ...  \
0   4.333844e-18 -5.544678e-18 -3.527045e-18 -2.230322e-17 -9.464323e-18  ...   
1   1.071920e-18 -8.969232e-18  2.481807e-18  5.587029e-18 -6.323524e-18  ...   
2  -2.234896e-17 -2.848297e-17 -7.615673e-18 -2.858059e-17 -2.918791e-17  ...   
3  -9.668881e-18  5.659504e-18 -3.799049e-18  7.146205e-18  6.621998e-18  ...   
4  -6.371805e-18 -7.304812e-18 -3.101835e-18 -2.526445e-17 -8.533010e-18  ...   
..           ...           ...           ...           ...           ...  ...   
75 -5.229836e-17 -6.156680e-17  2.015134e-17 -3.861454e-17  3.353806e-17  ...   
76 -1.606813e-16  3.486349e-16 -2.798004e-17 -8.240021e-17 -4.064488e-18  ...   
77  1.545369e-17  3.372716e-17  4.418819e-02  3.241330e-02  2.209549e-17  ...   
78 -3.822543e-17 -3.405337e-17 -5.225685e-17  8.297365e-17  7.679825e-17  ...   
79 -6.357078e-17 -4.792830e-18 -3.666657e-17 -8.644395e-18  4.568282e-17  ...   

        youtuber          yudi        yunani         zaman           zat  \
0  -1.678819e-18 -8.134566e-17  7.163781e-19 -5.968872e-17 -1.950547e-17   
1  -1.226715e-17  1.744990e-16  6.674196e-18 -2.092002e-17  1.135363e-17   
2  -4.859216e-18 -4.623445e-17 -1.460073e-17 -4.113700e-17  8.117794e-17   
3   1.489497e-17 -1.600452e-16 -2.296306e-18 -3.090400e-18 -4.253037e-17   
4   1.653832e-18 -3.593791e-17 -8.895964e-19 -1.614106e-17  5.967517e-17   
..           ...           ...           ...           ...           ...   
75  6.092284e-19 -1.173988e-18  1.291725e-18 -7.359022e-18  5.855708e-17   
76  4.760749e-18 -2.237183e-17 -8.373132e-18  1.998998e-19  4.164763e-02   
77  2.742904e-18  2.729987e-17  6.419186e-18  4.180955e-18  3.193314e-18   
78 -8.727616e-18  6.363166e-17  4.627447e-19  3.352087e-02  2.199152e-17   
79 -3.849659e-18  2.914556e-17 -1.898042e-17 -6.800828e-18  1.214645e-18   

            zeus       zhongli        zidane          zona          zone  
0   8.204388e-18 -1.620035e-17 -7.784572e-17 -1.826081e-17 -4.997494e-18  
1   1.358781e-17 -1.278003e-17  1.215120e-16  1.838114e-18 -8.900622e-18  
2  -1.876504e-17 -1.217356e-17 -3.510105e-17 -2.728767e-17 -8.470329e-18  
3  -1.467020e-17  1.490291e-17 -1.280036e-17  1.166246e-17 -3.121147e-17  
4   2.950269e-18 -8.278900e-18  8.623473e-17 -4.008901e-18 -1.190590e-17  
..           ...           ...           ...           ...           ...  
75  8.284988e-18 -1.278596e-17 -2.387955e-17 -2.681979e-17  4.843334e-18  
76 -9.120321e-18  1.350848e-17  5.887218e-17 -4.009648e-17 -1.816716e-17  
77  1.314868e-17  3.041695e-18 -2.038300e-17 -3.078562e-17 -1.152642e-17  
78  1.826355e-18  9.160661e-18 -1.381206e-16 -1.450465e-18 -6.326320e-17  
79 -2.611661e-17 -3.327145e-18 -4.297506e-17 -1.160890e-17 -8.998878e-18  

[80 rows x 4558 columns]

In [143]:
T1 = U.dot(Sigma_reduced)
T1_df = pd.DataFrame(T1, index=tfidf_df_loaded.index)

print("\nTransformation T1 (U * Reduced Sigma):\n")
T1_df


Transformation T1 (U * Reduced Sigma):



0         1         2         3         4         5         6     \
0  -0.249771  0.106801 -0.024859  0.023007 -0.083602  0.106787 -0.007283   
1  -0.216128  0.112726 -0.033813  0.016815 -0.012801 -0.304386  0.020837   
2  -0.499875 -0.303036  0.398435 -0.259188  0.124418 -0.048910 -0.094883   
3  -0.233678  0.124841 -0.002673 -0.015339 -0.015698  0.095711 -0.001263   
4  -0.446601 -0.227837  0.253549 -0.086201  0.034534 -0.006832  0.104357   
..       ...       ...       ...       ...       ...       ...       ...   
75 -0.235788  0.090483 -0.038281  0.037927 -0.110272 -0.018302  0.052179   
76 -0.387904  0.420605 -0.054097 -0.031120  0.127733  0.220733 -0.037166   
77 -0.302422 -0.169842 -0.006337  0.115288 -0.178775 -0.014922 -0.033038   
78 -0.305976  0.049333  0.011563 -0.036999 -0.044531 -0.017537  0.015656   
79 -0.247897  0.020635 -0.039532  0.041958 -0.132023  0.032477  0.036700   

        7         8         9     ...  2590  2591  2592  2593  2594  2595  \
0   0.133028 -0.040574  0.172213  ...   0.0   0.0   0.0   0.0   0.0   0.0   
1   0.150438 -0.018944 -0.167716  ...   0.0   0.0   0.0   0.0   0.0   0.0   
2  -0.096218 -0.184818  0.003918  ...   0.0   0.0   0.0   0.0   0.0   0.0   
3   0.161751 -0.035158 -0.110709  ...   0.0   0.0   0.0   0.0   0.0   0.0   
4   0.017729  0.465271 -0.012704  ...   0.0   0.0   0.0   0.0   0.0   0.0   
..       ...       ...       ...  ...   ...   ...   ...   ...   ...   ...   
75  0.366041 -0.149088  0.569127  ...   0.0   0.0   0.0   0.0   0.0   0.0   
76 -0.303389  0.036062  0.210507  ...   0.0   0.0   0.0   0.0   0.0   0.0   
77 -0.103636  0.108361 -0.027097  ...   0.0   0.0   0.0   0.0   0.0   0.0   
78  0.201761 -0.041986 -0.041351  ...   0.0   0.0   0.0   0.0   0.0   0.0   
79  0.286324 -0.073095  0.064960  ...   0.0   0.0   0.0   0.0   0.0   0.0   

    2596  2597  2598  2599  
0    0.0   0.0   0.0   0.0  
1    0.0   0.0   0.0   0.0  
2    0.0   0.0   0.0   0.0  
3    0.0   0.0   0.0   0.0  
4    0.0   0.0   0.0   0.0  
..   ...   ...   ...   ...  
75   0.0   0.0   0.0   0.0  
76   0.0   0.0   0.0   0.0  
77   0.0   0.0   0.0   0.0  
78   0.0   0.0   0.0   0.0  
79   0.0   0.0   0.0   0.0  

[80 rows x 2600 columns]

In [144]:
T2 = tfidf_df_loaded.values.dot(VT_reduced.T)
T2_df = pd.DataFrame(T2, index=tfidf_df_loaded.index)

print("\nTransformation T2 (Original Matrix * Reduced VT.T):\n")
T2_df


Transformation T2 (Original Matrix * Reduced VT.T):



0         1         2         3         4         5         6     \
0  -0.249771  0.106801 -0.024859  0.023007 -0.083602  0.106787 -0.007283   
1  -0.216128  0.112726 -0.033813  0.016815 -0.012801 -0.304386  0.020837   
2  -0.499875 -0.303036  0.398435 -0.259188  0.124418 -0.048910 -0.094883   
3  -0.233678  0.124841 -0.002673 -0.015339 -0.015698  0.095711 -0.001263   
4  -0.446601 -0.227837  0.253549 -0.086201  0.034534 -0.006832  0.104357   
..       ...       ...       ...       ...       ...       ...       ...   
75 -0.235788  0.090483 -0.038281  0.037927 -0.110272 -0.018302  0.052179   
76 -0.387904  0.420605 -0.054097 -0.031120  0.127733  0.220733 -0.037166   
77 -0.302422 -0.169842 -0.006337  0.115288 -0.178775 -0.014922 -0.033038   
78 -0.305976  0.049333  0.011563 -0.036999 -0.044531 -0.017537  0.015656   
79 -0.247897  0.020635 -0.039532  0.041958 -0.132023  0.032477  0.036700   

        7         8         9     ...          2590          2591  \
0   0.133028 -0.040574  0.172213  ... -3.252607e-19  9.486769e-19   
1   0.150438 -0.018944 -0.167716  ...  1.084202e-19  1.355253e-18   
2  -0.096218 -0.184818  0.003918  ... -2.168404e-19 -1.084202e-19   
3   0.161751 -0.035158 -0.110709  ... -7.318365e-19  3.794708e-19   
4   0.017729  0.465271 -0.012704  ... -4.336809e-19  1.572093e-18   
..       ...       ...       ...  ...           ...           ...   
75  0.366041 -0.149088  0.569127  ...  1.409463e-18 -2.276825e-18   
76 -0.303389  0.036062  0.210507  ... -9.757820e-19 -5.963112e-19   
77 -0.103636  0.108361 -0.027097  ... -2.298509e-17 -1.100465e-17   
78  0.201761 -0.041986 -0.041351  ... -9.107298e-18  9.324139e-18   
79  0.286324 -0.073095  0.064960  ...  1.082847e-17 -1.404042e-17   

            2592          2593          2594          2595          2596  \
0  -8.673617e-19 -1.301043e-17  8.131516e-20 -2.981556e-19 -4.336809e-19   
1   1.951564e-18 -5.421011e-19  2.168404e-19 -1.084202e-19 -3.794708e-19   
2   7.914676e-18 -4.336809e-18  1.084202e-19  8.131516e-20 -1.626303e-19   
3   1.301043e-18  1.734723e-18 -2.710505e-20 -7.860466e-19  3.794708e-19   
4   8.348357e-18  2.602085e-18  1.084202e-19  2.710505e-20  1.029992e-18   
..           ...           ...           ...           ...           ...   
75 -2.255141e-17  9.324139e-18  8.131516e-20  9.757820e-19 -4.987330e-18   
76 -3.252607e-18  2.688821e-17  0.000000e+00  6.505213e-18 -1.355253e-18   
77  1.203464e-16 -1.070650e-17  2.322564e-18  3.845530e-18  3.625301e-18   
78  1.859407e-17 -4.119968e-18  1.252254e-17  3.496552e-18  3.062871e-18   
79 -6.505213e-19  4.119968e-18 -2.439455e-19  1.259030e-17  2.428613e-17   

            2597          2598          2599  
0  -3.794708e-19 -1.084202e-19  3.794708e-19  
1  -1.029992e-18  1.084202e-19  4.878910e-19  
2  -6.505213e-19  6.505213e-19  6.505213e-19  
3   7.589415e-19 -1.517883e-18 -2.168404e-19  
4  -5.854692e-18  8.673617e-19  4.336809e-19  
..           ...           ...           ...  
75  1.897354e-18 -2.791821e-18 -4.250073e-17  
76  6.505213e-18  1.105886e-17 -4.336809e-19  
77 -6.234162e-18  1.165517e-18 -4.607859e-18  
78  5.963112e-18  1.409463e-18 -7.426785e-18  
79  1.680513e-18  6.396793e-18  1.734723e-18  

[80 rows x 2600 columns]

In [145]:
tf_idf_reconstructed = U @ Sigma @ VT

tf_idf_reconstructed_df = pd.DataFrame(tf_idf_reconstructed, columns=tfidf_df_loaded.columns)
tf_idf_reconstructed_df

00           000            01           016            02  \
0  -4.493176e-17 -1.304837e-16  1.279697e-17  4.618659e-18 -1.512589e-17   
1   6.244570e-17  1.154845e-17 -3.235835e-17  1.393941e-17 -1.077722e-17   
2  -4.648170e-17  8.450328e-02 -3.443020e-17 -1.220807e-17 -5.277015e-18   
3  -5.288999e-18  2.217892e-17 -3.727072e-17 -1.402316e-18  1.356004e-17   
4  -1.602518e-17  2.157461e-01  6.439623e-02 -5.681685e-18 -1.798378e-17   
..           ...           ...           ...           ...           ...   
75  8.229904e-18 -1.615885e-17  1.121133e-17  3.943648e-17 -2.019030e-17   
76 -4.114023e-17  2.639381e-02 -4.294288e-17 -9.105159e-17 -6.353679e-17   
77  1.296532e-01  1.127294e-01  4.605911e-17 -1.945730e-17  3.191790e-17   
78  8.673617e-18  6.071532e-17  7.741204e-17  4.087442e-17  3.191891e-16   
79  2.255141e-17 -2.775558e-17  7.199102e-17  1.626303e-17  2.927346e-17   

              05           062            08            09           090  ...  \
0   4.632000e-18 -4.661646e-18 -3.878564e-18 -2.360342e-17 -9.451617e-18  ...   
1   1.478920e-18 -9.832782e-18  2.955721e-18  4.712891e-18 -6.160471e-18  ...   
2  -2.249635e-17 -2.848995e-17 -7.219262e-18 -3.030853e-17 -2.832732e-17  ...   
3  -1.005333e-17  6.092814e-18 -2.763233e-18  7.158275e-18  6.608445e-18  ...   
4  -7.130323e-18 -7.304812e-18 -3.098447e-18 -2.266237e-17 -8.421202e-18  ...   
..           ...           ...           ...           ...           ...  ...   
75 -5.223716e-17 -6.185140e-17  2.060154e-17 -3.843836e-17  3.374643e-17  ...   
76 -1.608850e-16  3.488772e-16 -2.776235e-17 -8.108731e-17 -3.466482e-18  ...   
77  1.621221e-17  3.415787e-17  4.418819e-02  3.241330e-02  2.252959e-17  ...   
78 -3.927522e-17 -3.469447e-17 -5.030698e-17  8.315831e-17  7.762888e-17  ...   
79 -6.331741e-17 -5.204170e-18 -3.599551e-17 -1.301043e-17  4.640385e-17  ...   

        youtuber          yudi        yunani         zaman           zat  \
0  -1.779616e-18 -8.740702e-17  1.576964e-18 -6.098637e-17 -1.766233e-17   
1  -1.215789e-17  1.791390e-16  7.758398e-18 -2.070318e-17  1.135363e-17   
2  -4.669269e-18 -4.620734e-17 -1.552220e-17 -4.124542e-17  8.272801e-17   
3   1.490344e-17 -1.634875e-16 -1.425583e-18 -3.062871e-18 -4.403767e-17   
4   1.968928e-18 -3.854000e-17  8.993372e-19 -1.635621e-17  6.011223e-17   
..           ...           ...           ...           ...           ...   
75  8.758321e-19 -4.629882e-18  1.522118e-18 -7.386127e-18  5.833347e-17   
76  4.977589e-18 -2.562444e-17 -7.983497e-18 -1.694066e-20  4.164763e-02   
77  3.151386e-18  2.551094e-17  5.216399e-18  4.044582e-18  6.645821e-18   
78 -8.727827e-18  7.632783e-17 -5.204170e-18  3.352087e-02  2.775558e-17   
79 -3.794708e-18  2.081668e-17 -2.038300e-17 -6.722053e-18 -8.673617e-19   

            zeus       zhongli        zidane          zona          zone  
0   8.200999e-18 -1.641719e-17 -7.874018e-17 -1.798722e-17 -5.200782e-18  
1   1.348617e-17 -1.276648e-17  1.169448e-16  2.705476e-18 -8.737992e-18  
2  -1.833138e-17 -1.150864e-17 -3.501973e-17 -2.609507e-17 -8.036649e-18  
3  -1.522585e-17  1.468353e-17 -1.677464e-17  1.111273e-17 -3.140163e-17  
4   2.055828e-18 -7.409844e-18  8.992102e-17 -3.636207e-18 -1.168905e-17  
..           ...           ...           ...           ...           ...  
75  7.829284e-18 -1.279274e-17 -2.931412e-17 -2.638611e-17  5.385435e-18  
76 -8.605325e-18  1.316289e-17  5.388485e-17 -4.096384e-17 -1.833318e-17  
77  1.401264e-17  3.963267e-18 -3.060161e-17 -3.121931e-17 -1.103853e-17  
78  0.000000e+00  8.998878e-18 -1.457168e-16 -3.035766e-18 -6.320899e-17  
79 -2.515349e-17 -4.336809e-18 -4.163336e-17 -1.214306e-17 -9.324139e-18  

[80 rows x 4558 columns]

## Transformasi dengan Truncade SVD

In [158]:
# Inisialisasi TruncatedSVD
svd = TruncatedSVD(n_components=4000)

# Lakukan fit_transform untuk mendapatkan hasil langsung
result = svd.fit_transform(tfidf_df_loaded)

In [159]:
print(result.shape)

(80, 80)


In [161]:
result_df = pd.DataFrame(result, columns=tfidf_df_loaded.index)
result_df

0         1         2         3         4         5         6   \
0   0.249771  0.106801  0.024859  0.023007 -0.083602 -0.106787 -0.007283   
1   0.216128  0.112726  0.033813  0.016815 -0.012801  0.304386  0.020837   
2   0.499875 -0.303036 -0.398435 -0.259188  0.124418  0.048910 -0.094883   
3   0.233678  0.124841  0.002673 -0.015339 -0.015698 -0.095711 -0.001263   
4   0.446601 -0.227837 -0.253549 -0.086201  0.034534  0.006832  0.104357   
..       ...       ...       ...       ...       ...       ...       ...   
75  0.235788  0.090483  0.038281  0.037927 -0.110272  0.018302  0.052179   
76  0.387904  0.420605  0.054097 -0.031120  0.127733 -0.220733 -0.037166   
77  0.302422 -0.169842  0.006337  0.115288 -0.178775  0.014922 -0.033038   
78  0.305976  0.049333 -0.011563 -0.036999 -0.044531  0.017537  0.015656   
79  0.247897  0.020635  0.039532  0.041958 -0.132023 -0.032477  0.036700   

          7         8         9   ...        70        71        72        73  \
0  -0.133028  0.040574  0.172213  ...  0.000624 -0.013777 -0.016076  0.006192   
1  -0.150438  0.018944 -0.167716  ... -0.005930  0.069742 -0.013797 -0.044257   
2   0.096218  0.184818  0.003918  ... -0.053148  0.048431  0.262647 -0.077486   
3  -0.161751  0.035158 -0.110709  ... -0.005111 -0.003937 -0.003114 -0.000688   
4  -0.017729 -0.465271 -0.012704  ...  0.049607 -0.018028 -0.191390  0.072156   
..       ...       ...       ...  ...       ...       ...       ...       ...   
75 -0.366041  0.149088  0.569127  ... -0.000849 -0.026518  0.010360  0.022364   
76  0.303389 -0.036062  0.210507  ... -0.032014 -0.000221 -0.025191 -0.042658   
77  0.103636 -0.108361 -0.027097  ... -0.026055 -0.010713  0.000297 -0.004798   
78 -0.201761  0.041986 -0.041351  ... -0.017050  0.005052  0.014310 -0.024796   
79 -0.286324  0.073095  0.064960  ...  0.001940  0.006496  0.003478  0.011170   

          74        75        76        77        78        79  
0  -0.000130 -0.005078  0.000440  0.004719  0.001816  0.006923  
1  -0.203893  0.024491 -0.002089 -0.008209  0.004379  0.004697  
2   0.034313  0.009717  0.016365 -0.012644  0.014886 -0.003939  
3  -0.002169 -0.000157  0.003679 -0.000704 -0.002648  0.001030  
4  -0.010483 -0.010180  0.002622 -0.083334 -0.023448  0.005244  
..       ...       ...       ...       ...       ...       ...  
75  0.000168  0.008339 -0.002272  0.000369  0.000928 -0.003527  
76  0.106272 -0.018378 -0.001389  0.006271 -0.000255  0.006362  
77 -0.009787 -0.019285 -0.007957  0.007445  0.003089 -0.002611  
78  0.006499  0.002638 -0.006829  0.008162 -0.008245 -0.001907  
79  0.006476  0.000254 -0.007011  0.007139  0.001516  0.001885  

[80 rows x 80 columns]